# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skintype',
            name='image',
            field=models.ImageField(default=b'vol5-4.png', upload_to=None),
        ),
    ]
