# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin', '0003_contactpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
