# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-22 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin', '0005_auto_20171221_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='undertone',
            name='category',
            field=models.CharField(default=b'Fill', max_length=30),
        ),
        migrations.AddField(
            model_name='undertone',
            name='image_u',
            field=models.ImageField(default=b'vol5-4.png', upload_to=b''),
        ),
    ]
