# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-17 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin', '0008_auto_20180117_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='suggestion',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
