# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-17 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin', '0009_auto_20180117_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='created_by',
            field=models.TextField(max_length=30),
        ),
    ]
