# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-18 13:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin', '0010_auto_20180117_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='created_by',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='phone',
            field=models.CharField(max_length=17, null=True, validators=[django.core.validators.RegexValidator(message=b"Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex=b'^\\+?1?\\d{9,15}$')]),
        ),
    ]
